[package]
name = "ahq-store-app"
version = "0.4.0"
description = "AHQ Store on Tauri and Rust"
authors = ["AHQ Softwares"]
license = "ISC"
repository = "https://www.github.com/ahqsoftwares/tauri-ahq-store"
default-run = "ahq-store-app"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.2", features = ["fs-create-dir", "fs-read-file", "fs-write-file", "notification-all", "path-all", "updater", "window-close", "window-create", "window-maximize", "window-set-title"] }
tauri-plugin-single-instance = { git = "https://github.com/amrbashir/tauri-plugin-single-instance" }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
