[package]
name = "ahq-store-app"
version = "0.9.855"
description = "AHQ Store on Tauri and Rust"
authors = ["AHQ Softwares@AHQ Store"]
license = "ISC"
repository = "https://www.github.com/ahqsoftwares/tauri-ahq-store"
default-run = "ahq-store-app"
edition = "2021"
rust-version = "1.57"

[build-dependencies]
tauri-build = { version = "1.3", features = [] }

[dependencies]
serde_json = "1.0"
winapi-easy = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.3", features = ["dialog-all", "fs-create-dir", "fs-read-file", "fs-write-file", "global-shortcut-all", "http-all", "notification-all", "path-all", "system-tray", "updater", "window-all", "windows7-compat", "wry"] }
tauri-plugin-single-instance = { git = "https://github.com/amrbashir/tauri-plugin-single-instance" }
tauri-plugin-deep-link = {git = "https://github.com/FabianLars/tauri-plugin-deep-link"}
tauri-plugin-autostart = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev" }
downloader = "0.2.6"
mslnk = "0.1.8"
os-version = "0.2.0"
timer = "0.2.0"
time = "0.3"
minisign-verify = "0.2.1"
base64 = "0.21.0"
once_cell = "1.17.0"
windows = {version = "0.39.0", features= ["Win32_System_Com", "Win32_Foundation", "Win32_UI_Shell"] }
wry = "0.23.0"
crypter = "0.1.1"
is_elevated = "0.1.2"
open = "4.1.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
