[package]
name = "ahqstore_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcrypt = "0.14.0"
crypter = "0.1.1"
mslnk = "0.1.8"
reqwest = {version="0.11.18", features=["json", "blocking"]}
serde = {version = "1.0.163", features = ["serde_derive"] }
serde_json = "1.0.96"
threadpool = "1.8.1"
windows-service = "0.6.0"
ws = "0.9.2"
