[package]
name = "ahqstore_service"
version = "0.5.0"
description = "AHQ Store on Tauri and Rust"
authors = ["AHQ Store"]
license = "ISC"
repository = "https://www.github.com/ahqsoftwares/tauri-ahq-store"
edition = "2021"
rust-version = "1.57"

[dependencies]
bcrypt = "0.14.0"
crypter = "0.1.1"
downloader = "0.2.7"
mslnk = "0.1.8"
reqwest = {version="0.11.18", features=["json","blocking","stream"]}
serde = {version = "1.0.163", features = ["serde_derive"] }
serde_json = "1.0.96"
threadpool = "1.8.1"
windows-service = "0.6.0"
ws = "0.9.2"
