name: "publish"
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 1,5'

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - name: Cache store
      uses: actions/cache@v3.0.7
      with:
        key: ${{ runner.os }}-build
        path: |
          src-tauri/target/release
          node_modules
    - name: install app dependencies and build it
      run: yarn && yarn build
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAURI_PRIVATE_KEY: ${{secrets.TAURI}}
      with:
        tagName: __VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "AHQ Store __VERSION__"
        releaseBody: ""
        releaseDraft: true
        prerelease: false
  publish-release:
    runs-on: ubuntu-latest
    needs: [publish-tauri]

    steps:
      - name: Publish release
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.publish-tauri.outputs.releaseId }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: false
            })

